config/routes.rb
Rails.application.routes.draw do
  devise_for :doctors, path: 'doctors', controllers: {
    sessions: 'doctors/sessions'
  }

  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  namespace :users do
    resources :appointments, only: %i[create index]
    resource :profile, only: %i[show]
  end

  namespace :doctors do
    resources :appointments, only: %i[index update]
    resource :profile, only: %i[show]
  end

  namespace :admin do
    resource :profile, only: %i[show]
    resource :users, only: %i[show]
    resources :doctors, only: %i[create update index new]
    resources :categories, only: %i[create new]
  end

  resource :search_doctor, only: %i[new show edit create] do
    post '/', to: 'search_doctors#find'
  end

  root to: 'home#index'
end

app/models/doctor.rb
class Doctor < ApplicationRecord
  # VALIDATION = /^[0-9]{10}$/
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  validates_format_of :phone, with: /\A^[0-9]{10}\z/, on: :create

  belongs_to :category, optional: true

  has_many :appointments, dependent: :destroy
  has_many :users, through: :appointments

  def email_required?
    false
  end

  def email_changed?
    false
  end
end

app/controllers/admin/doctors_controller.rb
module Admin
  class DoctorsController < ApplicationController
    before_action :authenticate_doctor!

    def index
      authorize! :read, :index
      @doctors = Doctor.all
      @categories = Category.all
    end

    def new
    end

    def create
      @doctor = Doctor.new(doctor_params)

      if @doctor.save
        redirect_to admin_profile_path, notice: 'Doctor was successfully created.'
      else
        redirect_to admin_doctors_path, notice: 'Troubles with doctor creation'
      end
    end

    def update
      @doctor = Doctor.find(params[:id])

      if @doctor.update(doctor_params)
        redirect_to admin_profile_path, notice: 'Doctor was successfully updated.'
      else
        redirect_to admin_doctors_path, notice: 'Troubles with updating doctor'
      end
    end

    private

    def doctor_params
      params.permit(:phone, :password, :category, :category_id, :admin)
    end
  end
end

app/controllers/doctors/appointments_controller.rb
module Doctors
  class AppointmentsController < ApplicationController
    before_action :authenticate_doctor!

    authorize_resource

    def index
      @appointments = Appointment.where(doctor: current_doctor)
    end

    def update
      @appointment = Appointment.find(params[:id])
      # authorize! :edit, @appointment
      @appointment.status = false
      if @appointment.update(appointment_params)
        redirect_to doctors_appointments_path, notice: 'Appointment was successfully closed.'
      else
        redirect_to doctors_appointments_path, notice: 'Troubles with appointment'
      end
    end

    private

    def appointment_params
      params.require(:appointment).permit(:recomendation)
    end
  end
end

app/controllers/doctors/profiles_controller.rb
module Doctors
  class ProfilesController < ApplicationController
    before_action :authenticate_doctor!

    def show
    end
  end
end

app/controllers/doctors/sessions_controller.rb
# frozen_string_literal: true

class Doctors::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  def after_sign_in_path_for(resource)
    current_doctor.admin? ? admin_profile_path : doctors_profile_path
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/views/admin/doctors/index.html.erb
<h1>All DOCTORS</h1>

<% @doctors.each do |doctor| %>
  <b><p>Doctor id <%= doctor.id %></p></b>
  <p>Doctor phone <%= doctor.phone %></p>
  <p>Doctor category: <%= doctor.category.name if doctor.category.present? %></p>
  <br>

  <%= form_tag admin_doctor_path(doctor), method: :put, data: { turbo: false } do %>
    <p>Change doctors category</p>
    <%= select_tag :category_id, options_from_collection_for_select(@categories, :id, :name) %>
    <p><%= submit_tag "Update" %></p>
  <% end %>

  <br>
<% end %>

app/views/admin/doctors/new.html.erb
<h1>New Doctor</h1>

<%= form_with url: admin_doctors_path, method: :post do |f| %>
  <%= f.label :phone %><br />
  <%= f.text_field :phone, autofocus: true %><br />

  <%= f.label :password %><br />
  <%= f.password_field :password, autocomplete: "current-password" %><br />

  <%= f.label :category %><br />
  <%= f.collection_select :category_id, Category.all, :id, :name %><br />

  <%= f.label 'Admin?' %><br />
  <%= f.select :admin, [false, true] %><br />

  <br />

  <%= f.submit %>
<% end %>